[package]
name = "asynclog"
version = "1.0.0"
edition = "2021"
authors = ["kiven <kivensoft@gmail.com>"]
description = "A simple, asynchronous log library"

[dependencies]
log = "0.4"
chrono ="0.4"
parking_lot = "0.12"
lazy_static = "1.4"
